author = "uRick" # default first Author
description = "Hello,I am uRickðŸ˜„."
logo="https://gitee.com/uRick/oss/raw/master/blog/blog-favicon.png" 
#logo="/images/logo.png" # images/avatar.png
imageField = "image" # src
tocField = "toc" #value true or false
fromField = "from"  #post sources src
mainSections = ["post"] 
loading="/images/loading.svg"
enableTableContents=true 
googleTagManager = "" # GTM-XXXXXX
baiduAnalytics = ""
disableGoogleAdsense=true
enableLoading=true # Page loading

[dateFormat]
lastUpdated = "2006-01-02"
published = "2006-01-02"
[sidebar]
featureLimit = 5  
featureFeild = 'feature' 
categories = 8 
tags = 16

[search]
    enable = '' # only algolia
    appId=''
    searchKey=''

# social start
[social]
[social.github]
icon = "iconfont icon-github"
present="hugo-theme-uRickBlog."
url = "https://github.com/uRickLee/hugo-theme-uRickBlog"
[social.gitee]
icon = "iconfont icon-gitee"
url = "https://gitee.com/uRick/hugo-theme-uRickBlog"
present="hugo-theme-uRickBlog."
# social end

# footer start
[footer]
copyright = "@2019-2020, uRick,"
licence=true #CC By 4.0
enableShare=false 
[footer.about]
summary = "Hello I am uRick.ðŸ˜„"
coordinate = "Chengdu Â· China" 
email = "urickwork@gmail.com" 
phone = "+86 1234 5486 1125"

[footer.sub]
# footer end

#  comments start
[comments]
enable = false 
type = "gitalk" # Available: disqus, utterances,gitalk   
[comments.utterances] # https://utteranc.es/
issueTerm = "" 
label = "" # Optional
repo = "" 
theme = "" 
[comments.gitalk]
clientId = "" 
clientSecret = ""
repo = "" 
owner = "" 
admin = "" 
# comments end 